spring.application.name=travel-booking-app

spring.datasource.url=jdbc:h2:mem:ferdinand
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=fredo
spring.datasource.password=ferdinand

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enable=true
spring.h2.console.path=/h2-console

